name: BanCommands
api: [5.0.0]
main: Laith98Dev\BanCommands\Main
author: Laith98Dev
website: https://github.com/Laith98Dev
version: 2.0.0
description: Simple plugin to ban a command from a specific world.

commands:
  bancommands:
    description: BanCmd Command
    permission: bancommands.command
    aliases:
     - bc

permissions:
  bancommands.command:
    default: op
  bancommands.whitelist:
    default: op
